apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-api
spec:
  selector:
    matchLabels:
      app: lab-numbers-api
      version: v1
  template:
    metadata:
      labels:
        app: lab-numbers-api
        version: v1
    spec:
      containers:
        - name: api
          image: kiamol/ch03-numbers-api
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-web
spec:
  selector:
    matchLabels:
      app: lab-numbers-web
      version: v1
  template:
    metadata:
      labels:
        app: lab-numbers-web
        version: v1
    spec:
      containers:
        - name: web
          image: kiamol/ch03-numbers-web
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-web-v2
spec:
  selector:
    matchLabels:
      app: lab-numbers-web
      version: v2
  template:
    metadata:
      labels:
        app: lab-numbers-web
        version: v2
    spec:
      containers:
        - name: web
          image: kiamol/ch03-numbers-web:v2
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-numbers-api
    version: v1
  name: numbers-api
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lab-numbers-api
    version: v1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-numbers-web
    version: v2
  name: numbers-web-v2
spec:
  ports:
  - name: "8088"
    port: 8088
    protocol: TCP
    targetPort: 80
  selector:
    app: lab-numbers-web
    version: v1
  type: LoadBalancer