apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-api
spec:
  selector:
    matchLabels:
      app: lab-numbers-api
      version: v1
  template:
    metadata:
      labels:
        app: lab-numbers-api
        version: v1
    spec:
      containers:
        - name: api
          image: kiamol/ch03-numbers-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-web
spec:
  selector:
    matchLabels:
      app: lab-numbers-web
      version: v1
  template:
    metadata:
      labels:
        app: lab-numbers-web
        version: v1
    spec:
      containers:
        - name: web
          image: kiamol/ch03-numbers-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-web-v2
spec:
  selector:
    matchLabels:
      app: lab-numbers-web
      version: v2
  template:
    metadata:
      labels:
        app: lab-numbers-web
        version: v2
    spec:
      containers:
        - name: web
          image: kiamol/ch03-numbers-web:v2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  type: ClusterIP