name: Ch04 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch04.yaml"
      - "ch04/docker-images/**"
  schedule:
    - cron: "0 4 * * 0"

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch04
        working-directory: ./ch04/docker-images
        run: |
          docker-compose -f docker-compose.yml -f amd64.yml build --pull
          docker-compose -f docker-compose.yml -f amd64.yml push   

  build-arm64:
    runs-on: [self-hosted, Linux, ARM64, docker]
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch04
        working-directory: ./ch04/docker-images
        run: |
          docker compose -f docker-compose.yml -f arm64.yml build --pull
          docker compose -f docker-compose.yml -f arm64.yml push 

  push-manifests:
    runs-on: ubuntu-latest
    needs: ['build-amd64', 'build-arm64']
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch04
        working-directory: ./ch04/docker-images
        run: |
          ./push-manifests.ps1        
        shell: pwsh
