name: Ch13 Image Builds

on:
  push:
    paths:
      - ".github/workflows/ch13.yaml"
      - "ch13/docker-images/**"
  schedule:
    - cron: "0 13 * * 0"

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch13
        working-directory: ./ch13/docker-images
        run:  |
          docker-compose -f docker-compose.yml -f amd64.yml build --pull
          docker-compose -f docker-compose.yml -f amd64.yml push   

  build-arm64:
    runs-on: [self-hosted, Linux, ARM64, docker]
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ch13
        working-directory: ./ch13/docker-images
        run: |
          docker compose -f docker-compose.yml -f arm64.yml build --pull
          docker compose -f docker-compose.yml -f arm64.yml push 
